# Generated by Django 3.0.10 on 2020-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_sendtoemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
